package org.onap.sdc.dcae.enums;

public enum ArtifactType {
	DCAE_TOSCA,
	DCAE_JSON,
	DCAE_POLICY,
	DCAE_DOC,
	DCAE_EVENT,
	DCAE_INVENTORY_TOSCA,
	DCAE_INVENTORY_JSON,
	DCAE_INVENTORY_POLICY,
	DCAE_INVENTORY_DOC,
	DCAE_INVENTORY_BLUEPRINT,
	DCAE_INVENTORY_EVENT,
	OTHER
}
